#!/usr/bin/env bash
account="${1}"

user="$(pass "mail-${account}/mail" | awk '/user:/ { print $2 }')"
password="$(pass "mail-${account}/mail" | awk '/pass:/ { print $2 }')"

echo set my_user=\""${user}"\"
echo set my_pass=\""${password}"\"
