#!/usr/bin/env bash
account=${1}

pass_output=$(pass "mail-${account}/mail")
user=$(${pass_output} | awk '/user:/ { print $2 }')
pass=$(${pass_output} | awk '/pass:/ { print $2 }')

echo set my_user=\""${user}"\"
echo set my_pass=\""${pass}"\"
