#!/usr/bin/env zsh

local domain="${1}"

if [[ -z "${domain}" ]]; then
  echo "ERROR: No domain specified." >&2
fi

echo "Testing ${domain}…"
echo ""; # newline

local tmp
tmp=$(echo -e "GET / HTTP/1.0\\nEOT" | openssl s_client -connect "${domain}:443" 2>&1)

if [[ "${tmp}" = *"-----BEGIN CERTIFICATE-----"* ]]; then
  local certText
  certText=$(echo "${tmp}" \
    | openssl x509 -text -certopt "no_header, no_serial, no_version, \
    no_signame, no_validity, no_issuer, no_pubkey, no_sigdump, no_aux")
  echo "Common Name:"
  echo ""; # newline
  echo "${certText}" | grep "Subject:" | sed -e "s/^.*CN=//"
  echo ""; # newline
  echo "Subject Alternative Name(s):"
  echo ""; # newline
  echo "${certText}" | grep -A 1 "Subject Alternative Name:" \
    | sed -e "2s/DNS://g" -e "s/ //g" | tr "," "\\n" | tail -n +2
else
  echo "ERROR: Certificate not found." >&2
fi
