#!/usr/bin/env zsh

# Pdf Optimsing for screen use - use: gs-pdf-screen <file>

local file
file="$1"
if [[ -n "${file}" ]] && [[ -e "${file}" ]]; then
    gs \
        -sDEVICE=pdfwrite \
        -dCompatibilityLevel=1.4 \
        -dPDFSETTINGS=/screen \
        -dNOPAUSE \
        -dQUIET \
        -dBATCH \
        -sOutputFile=optimised.pdf \
        "${file}"
else
    echo "'${file}' is not a valid file."
fi
