#!/usr/bin/env zsh

# check if uri is up
local uri=$1

if curl -s --head --request GET "$uri" | grep "200 OK" >/dev/null; then
  notify-send --urgency=critical "$uri" "DOWN"
else
  notify-send --urgency=low "$uri" "UP"
fi
