#!/usr/bin/env bash
#
# Original: Eric Gebhart, 2013.02.17
#           https://github.com/EricGebhart/view_attachment
#
# Purpose:  To be called by mutt as indicated by .mailcap to handle mail attachments.
#
# Function: Copy the given file to a temporary directory so mutt
#           Won't delete it before it is read by the application.
#
#           Along the way, discern the file type or use the type
#           That is given.
#
#           Finally use 'open' or 'open -a' if the third argument is
#           given.
#
# Arguments:
#
#     "${filepath}" is the file
#     "${filetype}" is the type - for those times when file magic isn't enough.
#                      I frequently get html mail that has no extension
#                      and file can't figure out what it is.
#
#                      Set to '-' if you don't want the type to be discerned.
#                      Many applications can sniff out the type on their own.
#                      And they do a better job of it too.
#
#                      Open Office and MS Office for example.
#
#     "${open_with}" is open with.  as in open -a 'open with this .app' foo.xls
#
# Examples:  These are typical .mailcap entries which use this program.
#
#     Image/JPEG; /Users/vdanen/.mutt/view_attachment %s
#     Image/PNG; /Users/vdanen/.mutt/view_attachment %s
#     Image/GIF; /Users/vdanen/.mutt/view_attachment %s
#
#     Application/PDF; /Users/vdanen/.mutt/view_attachment %s
#
#         #This HTML example passes the type because file doesn't always work and
#         #there aren't always extensions.
#
#     text/html; /Users/vdanen/.mutt/view_attachment %s html
#
#         # If your Start OpenOffice.org.app is spelled with a space like this one, <--
#         # then you'll need to precede the space with a \ .  I found that too painful
#         # and renamed it with an _.
#
#     Application/vnd.ms-excel; /Users/vdanen/.mutt/view_attachment %s "-" '/Applications/OpenOffice.org1.1.2/Start_OpenOffice.org.app'
#     Application/msword; /Users/vdanen/.mutt/view_attachment %s "-" '/Applications/OpenOffice.org1.1.2/Start_OpenOffice.org.app'
#
# Modifications: Paul Monk
#   - Support Linux and OSX.
#   - Remove debugging
#   - General cleanup
#

# the tmp directory to use.
tmpdir="$(mktemp -d)" || exit

# Assign args
filepath="${1}"
filetype="${2}"
open_with="${3}"

# This gets the basic filename from the full pathname.
filename=$(basename "${filepath}")

# get rid of the extension and save the name for later.
#file=`echo $filename | cut -d"." -f1`
file=$(echo "${filename}" | sed 's/\.[^.]*$//')

# if the type is empty then try to figure it out.
if [[ -z "${filetype}" ]]; then
  #filetype=$(file -bi "${file}" | cut -d"/" -f2)
  filetype=$(file -bi "${file}" | sed -e 's/^[^\/]*\///' -e 's/;.*$//')
fi

# if the type is '-' then we don't want to mess with type.
# Otherwise we are rebuilding the name. Either from the
# type that was passed in or from the type we discerned.
if [[ "${filetype}" == "-" ]]; then
  new_file="${filename}"
else
  new_file="${file}.${filetype}"
fi
new_filepath="${tmpdir}/${new_file}"

# Copy the file to our new spot so mutt can't delete it
# before the app has a chance to view it.
cp "${filepath}" "${new_filepath}"

# If there's no 'open with' then we can let preview do it's thing.
# Otherwise we've been told what to use.  So do an open -a.
case $(uname) in
  "Linux")
    if [[ -z "${open_with}" ]]; then
      xdg-open "${new_filepath}"
    else
      # TODO - handle this case
      "{open_with}" "${new_filepath}"
    fi
    ;;
  "Darwin")
    if [[ -z "${open_with}" ]]; then
      open "${new_filepath}"
    else
      open -a "${open_with}" "${new_filepath}"
    fi
    ;;
esac
