#!/usr/bin/env bash

# shellcheck disable=1091,1090

# Archlinux loads bash completions from /etc automatically
# https://wiki.archlinux.org/index.php/Bash#Configuration_files

# Deal with other operating-systems...
# macOS / Darwin
if [[ "$KERNEL" == "Darwin" ]]; then
  # macOS Homebrew bash completions
  if [[ -f "${PREFIX:-/opt/homebrew}/etc/profile.d/bash_completion.sh" ]]; then
    # Load entire Homebrew installed software's bash completion
    # export BASH_COMPLETION_DEBUG=1
    source "${PREFIX:-/opt/homebrew}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "${PREFIX:-/opt/homebrew}/etc/bash_completion.d/"*; do
      [[ -r "$COMPLETION" ]] && source "$COMPLETION"
    done
  fi

  # Add tab completion for `defaults read|write NSGlobalDomain`
  # You could just use `-g` instead, but I like being explicit
  complete -W "NSGlobalDomain" defaults

  # Add `killall` tab completion for common apps
  complete -o "nospace" -W "Contacts Calendar Dock Finder Mail Safari iTunes SystemUIServer Terminal Twitter" killall
elif [[ -f "/etc/lsb-release" ]]; then
  if [[ -f "${PREFIX}/share/bash-completion/bash_completion" ]]; then
    source "${PREFIX}/share/bash-completion/bash_completion"
  elif [[ -f "/etc/bash_completion" ]]; then
    source "/etc/bash_completion"
  fi
fi
