#!/bin/sh

# Defaults.
#-----------------------
# Mysql
if command -v mysql >/dev/null 2>&1; then
  alias mysql='mysql --defaults-extra-file="${XDG_CONFIG_HOME}/mysql/config"'
fi

# Tmux
if command -v tmux >/dev/null 2>&1; then
  alias tmux='tmux -f "${XDG_CONFIG_HOME}/tmux/config"'
fi

# Wget
if command -v wget >/dev/null 2>&1; then
  alias wget='wget --hsts-file="${XDG_CACHE_HOME}/wget-hsts"'
fi

#  vim: set ft=sh ts=2 sw=4 tw=80 et :
