#!/bin/sh

LS_COLORS="$(vivid generate solarized-dark)"
export LS_COLORS

# Prefer eza if available
if command -v eza >/dev/null 2>&1; then
	ls="eza --group --git --group-directories-first --all"
else
	ls="LC_COLLATE=C ls --all"
fi

# shellcheck disable=SC2139
alias ls="${ls} --color=auto"

alias dir='dir --color=auto'
alias vdir='vdir --color=auto'

# Grep
export GREP_COLOR="37;45"             # BSD.
export GREP_COLORS="mt=${GREP_COLOR}" # GNU.
alias grep="grep --color=auto"
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# vim: set ft=sh ts=2 sw=2 tw=80 et :
