#!/bin/sh

#------------------------------------------------------------------------------
# This file contains most of our environment exports.
#------------------------------------------------------------------------------
# XDG directories
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"

# Set Kernel.
KERNEL="$(uname -s)"
export KERNEL

# Set Arch.
ARCH="$(uname -m)"
export ARCH

# Homebrew opts
# Abort installation of cask if no checksum is defined
export HOMEBREW_CASK_OPTS="--require-sha"
# Force use of our curlrc
export HOMEBREW_CURLRC="1"
# Force homebrew software
export HOMEBREW_FORCE_BREWED_CURL="1"
export HOMEBREW_FORCE_BREWED_GIT="1"
# brew upgrade always assumes --cleanup has been passed
export HOMEBREW_INSTALL_CLEANUP="1"
# Disable anonymous statistics collections
export HOMEBREW_NO_ANALYTICS="1"
# Disable automatic updates to keep in control of brew updates
export HOMEBREW_NO_AUTO_UPDATE="1"
# Disable hints to avoid cluttering the terminal
export HOMEBREW_NO_ENV_HINTS="1"

# When checking out a public repository, by default, your username is always sent, not now.
export HOMEBREW_NO_GITHUB_API="1"
# Avoid protocol downgrades from HTTPS to HTTP via redirect
export HOMEBREW_NO_INSECURE_REDIRECT="1"


# macOS
if [ "$KERNEL" = "Darwin" ]; then
	# Set Default PATH
	export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"

	# Prefix
	# Cater for M1 arch
	BREW_ARM_PREFIX="/opt/homebrew"
	BREW_X86_PREFIX="/usr/local"
	if [ "$ARCH" = "arm64" ]; then
		export BREW_PREFIX="$BREW_ARM_PREFIX"
		export PREFIX="$BREW_PREFIX"
		# Add both Arm and Intel paths, favour native arm first.
		export PATH="${BREW_PREFIX}/bin:${BREW_PREFIX}/sbin:${BREW_X86_PREFIX}/bin:${BREW_X86_PREFIX}/sbin:${PATH}"
	else
		export BREW_PREFIX="$BREW_X86_PREFIX"
		export PREFIX="$BREW_PREFIX"
		export PATH="${BREW_PREFIX}/bin:${BREW_PREFIX}/sbin:${PATH}"
	fi

	# XDG
	export XDG_RUNTIME_DIR="/tmp/run"
	[ ! -d "$XDG_RUNTIME_DIR" ] && mkdir -m 0700 "$XDG_RUNTIME_DIR"

	# Use homebrew GNU tools instead of system BSD
	# =============
	# Coreutils
	export PATH="${BREW_PREFIX}/opt/uutils-coreutils/libexec/gnubin:${PATH}"
	export MANPATH="${BREW_PREFIX}/opt/uutils-coreutils/libexec/gnuman:${MANPATH}"

	# Sed
	export PATH="${BREW_PREFIX}/opt/gnu-sed/libexec/gnubin:${PATH}"
	export MANPATH="${BREW_PREFIX}/opt/gnu-sed/libexec/gnuman:${MANPATH}"

	# Use homebrew tools for build support
	# =============
	CPPFLAGS="-I${BREW_PREFIX}/include"
	LDFLAGS="-L${BREW_PREFIX}/lib"

	# Memcached
	export LIBMEMCACHED="$BREW_PREFIX"

	# Openssl
	export PATH="${BREW_PREFIX}/opt/openssl@3/bin:${PATH}"
	CPPFLAGS="-I${BREW_PREFIX}/opt/openssl@3/include ${CPPFLAGS}"
	LDFLAGS="-L${BREW_PREFIX}/opt/openssl@3/lib ${LDFLAGS}"

	# Zlib
	CPPFLAGS="-I${BREW_PREFIX}/opt/zlib/include ${CPPFLAGS}"
	LDFLAGS="-L${BREW_PREFIX}/opt/zlib/lib ${LDFLAGS}"

	# Bzip2
	CPPFLAGS="-I${BREW_PREFIX}/opt/bzip2/include ${CPPFLAGS}"
	LDFLAGS="-L${BREW_PREFIX}/opt/bzip2/lib ${LDFLAGS}"

	# Readline
	CPPFLAGS="-I${BREW_PREFIX}/opt/readline/include ${CPPFLAGS}"
	LDFLAGS="-L${BREW_PREFIX}/opt/readline/lib ${LDFLAGS}"

	# Xcode
	# BUILD Flags
	# Ensure CommandLineTools SDK is used correctly
	CFLAGS="-I$(xcrun --show-sdk-path)/usr/include -I${BREW_PREFIX}/include -I/usr/local/include"
	export CFLAGS
	export CPPFLAGS
	export LDFLAGS

	# Android
	export ANDROID_HOME="${HOME}/Library/Android/sdk"
	export PATH="${PATH}:${ANDROID_HOME}/emulator"
	export PATH="${PATH}:${ANDROID_HOME}/tools"
	export PATH="${PATH}:${ANDROID_HOME}/tools/bin"
	export PATH="${PATH}:${ANDROID_HOME}/platform-tools"

	# Set defaults
	export BROWSER="open"
	export TERMINAL="open"

	# CPU
	CPU_CORES="$(sysctl -n hw.ncpu)"
else
	# Prefix
	export BREW_PREFIX="/home/linuxbrew/.linuxbrew"
	export PREFIX="/usr"
	export PATH="${BREW_PREFIX}/bin:${BREW_PREFIX}/sbin:${PATH}"

	# Set defaults
	export BROWSER="${PREFIX}/bin/chromium"
	export TERMINAL="${PREFIX}/bin/kitty"

	# CPU
	CPU_CORES="$(nproc)"

	# GTK 2: Pull GTK2 RC files from the standard config location, similar to gtk-3.0
	export GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/gtkrc"

	# GTK 3: HiDPI.
	# Scale UI elements by a factor of two
	# export GDK_SCALE="2"
	# Undo text scaling.
	# export GDK_DPI_SCALE="0.5"

	# QT 5.6: HiDPI
	# export QT_AUTO_SCREEN_SCALE_FACTOR="1"

	# Qt: Forces QT to use GTK icons
	export DESKTOP_SESSION="gnome"

	# XSECURELOCK
	export XSECURELOCK_FONT="-misc-roboto-medium-r-normal--0-0-0-0-p-0-iso10646-1"
	export XSECURELOCK_PASSWORD_PROMPT=time_hex
	export XSECURELOCK_SHOW_HOSTNAME="0"
	export XSECURELOCK_SHOW_USERNAME="0"
	export XSECURELOCK_WANT_FIRST_KEYPRESS="1"

	# Zeal: https://github.com/zealdocs/zeal/issues/172
	export QT_QPA_PLATFORMTHEME="gtk2"
fi

# Local Bins (user and system)
export PATH="${HOME}/.local/bin:/usr/local/bin:${PATH}"

# Defaults
export LC_ALL="en_GB.UTF-8"
export LANG="en_GB.UTF-8"
export PAGER="less"
export MANPAGER="less -X"

# Defaults: Editor
if command -v lvim >/dev/null 2>&1; then
	export EDITOR="lvim"
elif command -v nvim >/dev/null 2>&1; then
	export EDITOR="nvim"
elif command -v vim >/dev/null 2>&1; then
	export EDITOR="vim"
else
	export EDITOR="vi"
	# Don’t clear the screen after quitting a manual page
fi
export VISUAL="$EDITOR"

# Ack configuration
if [ -f "${XDG_CONFIG_HOME}/ack/ackrc" ]; then
	export ACKRC="${XDG_CONFIG_HOME}/ack/ackrc"
fi
export ACK_PAGER_COLOR="less -x4SRFX"

# Bat
export BAT_THEME="TwoDark"

# Curl
export CURL_HOME="${XDG_CONFIG_HOME}/curl"
# .netrc
if [ -f "${XDG_CONFIG_HOME}/netrc/config" ]; then
	export CURLOPT_NETRC_FILE="${XDG_CONFIG_HOME}/netrc/config"
fi

# Docker
export DOCKER_CONFIG="${XDG_CONFIG_HOME}/docker"

if command -v docker-machine >/dev/null 2>&1; then
	export MACHINE_STORAGE_PATH="${XDG_DATA_HOME}/docker-machine"
fi

# Facebook PathPicker
export FPP_DIR="${XDG_CACHE_HOME}/fpp"

# GCC
export GCC_COLORS="1"

# Git
# This is used in multiple aliases in the config file.
export GIT_REVIEW_BASE="master"

# GNUPG
export GNUPGHOME="${XDG_CONFIG_HOME}/gnupg"

# GO configuration
export GOPATH="${XDG_DATA_HOME}/go"
export PATH="${PATH}:${GOPATH}/bin"

# Haskell cabal configuration
export PATH="${PATH}:${HOME}/.cabal/bin"

# HTTPIE
export HTTPIE_CONFIG_DIR="${XDG_CONFIG_HOME}/httpie"

# JAVA openjdk.
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=\"${XDG_CONFIG_HOME}/java\""

# LESS
export LESS="--tabs=4 --quit-if-one-screen --ignore-case --no-init --QUIET --LONG-PROMPT --RAW-CONTROL-CHARS"
export LESSCHARSET="UTF-8"
export LESSHISTFILE="${XDG_CACHE_HOME}/less/history"
export LESSKEY="${XDG_CONFIG_HOME}/less/lesskey/output"

# Lua user config
export LUAROCKS_CONFIG="${XDG_CONFIG_HOME}/luarocks/config.lua"

# Make
export MAKEFLAGS="-j ${CPU_CORES}"

# MariaDB / MySQL
export MYSQL_HISTFILE="${XDG_DATA_HOME}/mysql/history"

# MPV
export MPV_HOME="${XDG_CONFIG_HOME}/mpv"

# Ncurses
# Look for terminfo files under data
if [ -d "${XDG_DATA_HOME}/terminfo" ]; then
	export TERMINFO="${XDG_DATA_HOME}/terminfo"
	export TERMINFO_DIRS="${XDG_DATA_HOME}/terminfo:${PREFIX}/share/terminfo"
fi

# Node / NPM / Nave
export BABEL_CACHE_PATH="${XDG_CACHE_HOME}/babel.json"
export NODE_REPL_HISTORY="${XDG_DATA_HOME}/node/repl_history"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/npmrc"
export NAVE_DIR="${XDG_DATA_HOME}/nave"
export NAVE_JOBS="$CPU_CORES"
export PATH="${PATH}:${XDG_DATA_HOME}/npm/bin"

# NotMuch
export NOTMUCH_CONFIG="${XDG_CONFIG_HOME}/notmuch/config"
export NMBGIT="${XDG_DATA_HOME}/notmuch/nmbug"

# Pass
export PASSWORD_STORE_DIR="${XDG_DATA_HOME}/pass"

# Postgresql
export PSQLRC="${XDG_CONFIG_HOME}/pg/psqlrc"
export PSQL_HISTORY="${XDG_CACHE_HOME}/pg/psql_history"
export PGPASSFILE="${XDG_CONFIG_HOME}/pg/pgpass"
export PGSERVICEFILE="${XDG_CONFIG_HOME}/pg/pg_service.conf"

# Python
export VIRTUAL_ENV_DISABLE_PROMPT="1"
export IPYTHONDIR="${XDG_CONFIG_HOME}/ipython"
export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME}/jupyter"
export PYLINTHOME="${XDG_CACHE_HOME}/pylint"
export PYTHON_EGG_CACHE="${XDG_CACHE_HOME}/python_eggs"

export PYTHONASYNCIODEBUG="1"
export PYTHONBREAKPOINT="ipdb.set_trace"
export PYTHON_CONFIGURE_OPTS='--enable-optimizations --with-lto'
export PYTHON_CFLAGS='-march=native -mtune=native'
export PYTHONFAULTHANDLER="1"
export PYTHONUSERBASE="${XDG_DATA_HOME}/python"
export PATH="${PATH}:${PYTHONUSERBASE}/bin"

export PYENV_ROOT="${XDG_DATA_HOME}/pyenv"
export PATH="${PYENV_ROOT}/shims:${PATH}"

# RCM
export RCRC="${XDG_CONFIG_HOME}/rcm/rcrc"

# Readline
export INPUTRC="${XDG_CONFIG_HOME}/readline/inputrc"

# Ripgrep
export RIPGREP_CONFIG_PATH="${XDG_CONFIG_HOME}/ripgrep/rc"

# Ruby: Always install ruby gems local to the user
export GEMRC="${XDG_CONFIG_HOME}/gem/gemrc"
GEM_HOME="${XDG_DATA_HOME}/gem/$(ruby -e 'puts RbConfig::CONFIG["ruby_version"]')"
export GEM_HOME
export GEM_PATH="${GEM_HOME}"
export GEM_SPEC_CACHE="${XDG_CACHE_HOME}/gem/specs"
export PATH="${PATH}:${GEM_HOME}/bin"

# Rust: Cargo configuration
export CARGO_BUILD_JOBS="$CPU_CORES"
export CARGO_HOME="${XDG_DATA_HOME}/cargo"
export PATH="${PATH}:${CARGO_HOME}/bin"
export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"

# Sudo
export SUDO_PROMPT="sudo password for %p@[30;43m%h[m: "

# sshrc
export SSHHOME="${XDG_CONFIG_HOME}/sshrc"

# Task
export TASKDATA="${XDG_DATA_HOME}/task"
export TASKRC="${XDG_CONFIG_HOME}/task/taskr"

# Tmux
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export TMUXP_CONFIGDIR="${XDG_CONFIG_HOME}/tmuxp"

# Virtualbox
export VBOX_USER_HOME="${XDG_CONFIG_HOME}/virtualbox"

# Wine
if command -v wine >/dev/null 2>&1; then
	[ ! -d "${XDG_DATA_HOME}/wineprefixes" ] && mkdir -m 0700 "${XDG_DATA_HOME}/wineprefixes"
	export WINEPREFIX="${XDG_DATA_HOME}/wineprefixes/default"
fi

# Wget
if [ -f "${XDG_CONFIG_HOME}/wget/config" ]; then
	export WGETRC="${XDG_CONFIG_HOME}/wget/config"
fi

# vim: set ft=sh ts=2 sw=2 tw=80 et :
