#!/usr/bin/env zsh

#------------------------------------------------------------------------------
# If you use several different terminal emulators, it's likely, that you've
# run into the problem, that pressing a special key like PageDown will just
# display a tilde instead of doing what it's supposed to.

# There is a function described in zshcontrib(1) that reads and stores
# keydefinitions for special keys, if it recognizes a terminal, it hasn't seen
# before.

# http://zshwiki.org/home/zle/bindkeys

# create a zkbd compatible hash;
# to add other keys to this hash, see: man 5 terminfo
#
#------------------------------------------------------------------------------
# Ctrl-R => history-incremental-search-backward
bindkey "$key_info[Control]R" history-incremental-search-backward

# Ctrl+right => forward word
bindkey "$key_info[Control]$key_info[Right]" forward-word

# Ctrl+left => backward word
bindkey "$key_info[Control]$key_info[Left]" backward-word

# Ctrl+Backspace => delete a previous word
bindkey "$key_info[Control]$key_info[Backspace]" backward-kill-word

# VI Keybindings
# ----------------
bindkey -M viins 'kj' vi-cmd-mode

# View manpage while editing a command
bindkey -M vicmd 'K' run-help

# Make Vi mode transitions faster (KEYTIMEOUT is in hundredths of a second)
export KEYTIMEOUT=1
