#!/usr/bin/env zsh

#------------------------------------------------------------------------------
# Plugins
#------------------------------------------------------------------------------
# Load antigen
# https://github.com/zsh-users/antigen/wiki/Configuration
export ADOTDIR="${XDG_DATA_HOME}/zsh/antigen"
export ANTIGEN_COMPDUMP="${ADOTDIR}/.zcompdump-${HOST}-${ZSH_VERSION}"

# Init ZSH
if [[ "${KERNEL}" == "Darwin" ]]; then
  source "${PREFIX}/share/antigen/antigen.zsh"
else
  source "${PREFIX}/share/zsh-antigen/antigen.zsh"
fi

# Setup
antigen use prezto

# Bundles
antigen bundles <<EOB
    robbyrussell/oh-my-zsh plugins/encode64
    robbyrussell/oh-my-zsh plugins/fancy-ctrl-z
    hlissner/zsh-autopair
    marzocchi/zsh-notify
    mafredri/zsh-async
EOB

# Plugins Config
# ----------------
# Prezto
# Color output (auto set to 'no' on dumb terminals).
zstyle ':prezto:*:*' color 'yes'

# Set the Prezto modules to load (browse modules).
# The order matters.
zstyle ':prezto:load' pmodule \
  'prompt' \
  'environment' \
  'editor'      \
  'history'     \
  'directory'   \
  'completion'  \
  'archive' \
  'syntax-highlighting' \
  'history-substring-search' \
  'autosuggestions'

# Set theme
zstyle ':prezto:module:prompt' theme 'powerlevel10k'

# Auto convert .... to ../..
zstyle ':prezto:module:editor' dot-expansion 'yes'
# Set the key mapping style to 'emacs' or 'vi'.
zstyle ':prezto:module:editor' key-bindings 'vi'


# Zoxide
_ZO_DATA="${XDG_DATA_HOME}/zsh/zo"
if [[ ! -f "${_ZO_DATA}" ]]; then
  touch "${_ZO_DATA}"
fi
export _ZO_DATA


# zsh-notify
zstyle ':notify:*' command-complete-timeout 15
zstyle ':notify:*' error-title 'Error'
zstyle ':notify:*' success-title 'Success'
if [[ ! "${KERNEL}" == "Darwin" ]]; then
  zstyle ':notify:*' error-icon '/usr/share/icons/Adwaita/256x256/status/dialog-error.png'
  zstyle ':notify:*' success-icon '/usr/share/icons/Adwaita/256x256/status/dialog-information.png'
fi


# Finalize
# ----------------
# Tell Antigen that you're done.
antigen apply
