#!/usr/bin/env zsh

#------------------------------------------------------------------------------
# Plugins - .antigenrc file.
#------------------------------------------------------------------------------
antigen use prezto

# Bundles
antigen bundles <<EOB
    robbyrussell/oh-my-zsh plugins/encode64
    robbyrussell/oh-my-zsh plugins/fancy-ctrl-z
    hlissner/zsh-autopair
    marzocchi/zsh-notify
    jreese/zsh-titles
    rupa/z
    changyuheng/fz
    mafredri/zsh-async
EOB


# Prompt
# ----------------
# Set theme
antigen theme "geometry-zsh/geometry"

# Set geometry plugins.
export GEOMETRY_PROMPT_PLUGINS=(exec_time jobs hostname virtualenv git)

# Symbols
export GEOMETRY_SYMBOL_PROMPT="$"                  # default prompt symbol
export GEOMETRY_SYMBOL_RPROMPT=">"                 # multiline prompts
export GEOMETRY_SYMBOL_EXIT_VALUE="!"              # displayed when exit value is != 0
export GEOMETRY_SYMBOL_ROOT="#"                    # when logged in user is root

# Colours
export GEOMETRY_COLOR_EXIT_VALUE="magenta"         # prompt symbol color when exit value is != 0
export GEOMETRY_COLOR_PROMPT="white"               # prompt symbol color
export GEOMETRY_COLOR_ROOT="red"                   # root prompt symbol color
export GEOMETRY_COLOR_DIR="blue"                   # current directory color

# Misc
export GEOMETRY_PROMPT_PREFIX=""                   # prefix prompt with a new line
export GEOMETRY_PROMPT_SUFFIX=""                   # suffix prompt
export GEOMETRY_PROMPT_PREFIX_SPACER=" "           # string to place between prefix and symbol
export GEOMETRY_SYMBOL_SPACER=" "                  # string to place between symbol and directory
export GEOMETRY_DIR_SPACER=" "                     # string to place between directory and suffix
export GEOMETRY_PLUGIN_SEPARATOR=" "               # use ' ' to separate right prompt parts


# Plugins Config
# ----------------
# Prezto
# Color output (auto set to 'no' on dumb terminals).
zstyle ':prezto:*:*' color 'yes'

# Set the Prezto modules to load (browse modules).
# The order matters.
zstyle ':prezto:load' pmodule \
  'environment' \
  'editor'      \
  'history'     \
  'directory'   \
  'completion'  \
  'archive' \
  'syntax-highlighting' \
  'history-substring-search' \
  'autosuggestions'

# Auto convert .... to ../..
zstyle ':prezto:module:editor' dot-expansion 'yes'
# Set the key mapping style to 'emacs' or 'vi'.
zstyle ':prezto:module:editor' key-bindings 'vi'


# Z
[[ -f "${XDG_DATA_HOME}/zsh/z" ]] || touch "${XDG_DATA_HOME}/zsh/z"
export _Z_DATA="${XDG_DATA_HOME}/zsh/z"


# zsh-notify
zstyle ':notify:*' command-complete-timeout 15
zstyle ':notify:*' error-title 'Error'
zstyle ':notify:*' success-title 'Success'
if [[ ! "${KERNEL}" == "Darwin" ]]; then
  zstyle ':notify:*' error-icon '/usr/share/icons/Adwaita/256x256/status/dialog-error.png'
  zstyle ':notify:*' success-icon '/usr/share/icons/Adwaita/256x256/status/dialog-information.png'
fi


# Plugins Finalize
# ----------------
# Tell Antigen that you're done.
antigen apply
