#!/usr/bin/env zsh

# shellcheck disable=SC2148
# shellcheck source=/dev/null

#------------------------------------------------------------------------------
# zprofile
#------------------------------------------------------------------------------
[[ -s "${HOME}/.profile" ]] && source "${HOME}/.profile"
