#!/usr/bin/env zsh

alias brewi="brew install"
alias brewo="brew update && echo '\nOutdated Pkgs:' && brew outdated && echo '\nOutdated Casks:' && brew outdated --cask"
alias brewup="brew upgrade && brew cask upgrade"
alias brewr="brew uninstall"

alias brewp="brew pin"
alias brewpl="brew list --pinned"

alias brewq="brew search"
