#!/usr/bin/env zsh

#-------------------------------------------
# FZF
#-------------------------------------------

# Contrib
#-------------------------
# keybindings
if [[ -s "/usr/share/fzf/key-bindings.zsh" ]]; then
  source "/usr/share/fzf/key-bindings.zsh"
fi

# completions
if [[ -s "/usr/share/fzf/completion.zsh" ]]; then
  source "/usr/share/fzf/completion.zsh"
fi

# General
#-------------------------
# Default Command
if (( $+commands[rg] )); then
  export FZF_DEFAULT_COMMAND="rg --hidden --files --smart-case --follow "
elif (( $+commands[ag] )); then
  export FZF_DEFAULT_COMMAND="ag --hidden --follow --nogroup  -g "
fi

# Default Opts
_gen_fzf_default_opts() {
  local base03="234"
  local base02="235"
  local base01="240"
  local base00="241"
  local base0="244"
  local base1="245"
  local base2="254"
  local base3="230"
  local yellow="136"
  local orange="166"
  local red="160"
  local magenta="125"
  local violet="61"
  local blue="33"
  local cyan="37"
  local green="64"

  # Solarized Dark color scheme
  export FZF_DEFAULT_OPTS="
    --color fg:-1,bg:-1,hl:${blue},fg+:${base2},bg+:${base02},hl+:${blue}
    --color info:${yellow},prompt:${yellow},pointer:${base3},marker:${base3},spinner:${yellow}
    --reverse --height 50% --multi
  "
}
_gen_fzf_default_opts

# Alt C:
if (( $+commands[fd] )); then
  export FZF_ALT_C_COMMAND="fd --type d --hidden --follow "
fi
export FZF_ALT_C_OPTS="--select-1 --exit-0"

# Ctrl T:
# Automatically select if only 1 and exit if list is empty.
export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
export FZF_CTRL_T_OPTS="--select-1 --exit-0"

# Keybindings
#-------------------------
# Use fzf for history if available
fzf-history-widget-accept() {
    fzf-history-widget
    zle accept-line
}
zle     -N     fzf-history-widget-accept
bindkey '^X^R' fzf-history-widget-accept


# Completions
#-------------------------
export FZF_COMPLETION_TRIGGER=""

if (( $+commands[fd] )); then
  # Use fd (https://github.com/sharkdp/fd) instead of the default find
  # command for listing path candidates.
  # - The first argument to the function ($1) is the base path to start traversal
  # - See the source code (completion.{bash,zsh}) for the details.
  _fzf_compgen_path() {
    fd --hidden --follow . "${1}"
  }

  # Use fd to generate the list for directory completion
  _fzf_compgen_dir() {
    fd --type d --hidden --follow . "${1}"
  }
fi
