#!/usr/bin/env zsh
alias paci="pacman -Sy"
alias paci!="paci -dd"
alias pacr="pacman -Rs"
alias pacr!="pacr -dd"
alias pacf="pacman -U"
alias pacu="pacman -Syu"
alias pacq="pacman -Si"
alias pacQ="pacman -Qo"

pac() {
  sudo pacman "$@"
}
compdef pac=pacman

pacs() {
  aur search -n -k NumVotes "$@"
  pacman -Ss "$@"
}

pacs!() {
  aur search -k NumVotes "$@"
  pacman -Ss "$@"
}

aur-official() {
  comm -12 <(pacman -Sl | grep -v ${LOGNAME} | cut -d' ' -f2 | sort) \
    <(aur sync --list 2>/dev/null | cut -f2 | sort)
}

aurs() {
  aur sync -sc "$@"
  post_aur
}
alias aurs!="aurs --no-ver-shallow"

aurb() {
  aur build -sc -d "${LOGNAME}" "$@"
  post_aur
}

auru() {
  aur vercmp-devel "$@" | cut -d: -f1 | xargs aur sync -scu --no-ver-shallow "$@"
  post_aur
}

post_aur() {
  sudo pacman -Sy
  find "${XDG_CACHE_HOME}/aurutils/sync" -name .git -execdir git clean -fx \;
  find "/var/cache/pacman/${LOGNAME}" -name "*~" -delete
}
