#!/bin/sh

XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

# fzf
mkdir -p "${XDG_DATA_HOME}/fzf"

# npm
mkdir -p "${XDG_CACHE_HOME}/npm"
mkdir -p "${XDG_CONFIG_HOME}/npm"
mkdir -p "${XDG_DATA_HOME}/npm"

# postgres
mkdir -p "${XDG_CACHE_HOME}/pg"
