#!/bin/sh

# Set Variables if not currently defined.
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

# fzf
mkdir -p "${XDG_DATA_HOME}/fzf"

# npm
mkdir -p "${XDG_CACHE_HOME}/npm"
mkdir -p "${XDG_CONFIG_HOME}/npm"
mkdir -p "${XDG_DATA_HOME}/npm"

# postgres
mkdir -p "${XDG_CACHE_HOME}/pg"
