#!/bin/bash
# Create XDG directories that tools expect to exist.
set -o errexit -o errtrace -o pipefail -o nounset

readonly XDG_CACHE_HOME="${XDG_CACHE_HOME:-${HOME}/.cache}"
readonly XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
readonly XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"

# fzf
mkdir -p "${XDG_DATA_HOME}/fzf"

# npm
mkdir -p "${XDG_CACHE_HOME}/npm"
mkdir -p "${XDG_CONFIG_HOME}/npm"
mkdir -p "${XDG_DATA_HOME}/npm"

# postgres
mkdir -p "${XDG_CACHE_HOME}/pg"
