#!/bin/sh
if [ "$(uname -s)" = "Darwin" ]; then
  # Force use of BSD installed variant.
  /usr/bin/sed -i "" -e \
    "s#/usr/bin/pinentry-gnome3#\${PREFIX}/bin/pinentry-mac#g" \
    "${XDG_CONFIG_HOME}/gnupg/gpg-agent.conf"
fi
