#!/bin/bash
# Import personal GPG key and ensure GNUPGHOME permissions.
set -o errexit -o errtrace -o pipefail -o nounset

readonly GNUPGHOME="${XDG_CONFIG_HOME:-${HOME}/.config}/gnupg"
readonly MY_GPG_KEY_ID="0x06E2E2310CB5DB04"

if ! gpg -k | grep "${MY_GPG_KEY_ID}" >/dev/null; then
  curl -s https://keybase.io/pmonk/key.asc | gpg --import
  if gpg -k | grep "${MY_GPG_KEY_ID}" >/dev/null; then
    gpg --list-keys --fingerprint --with-colons |
      sed -E -n -e 's/^fpr:::::::::([0-9A-F]+):$/\1:6:/p' |
      gpg --import-ownertrust
  fi
fi

chmod -R 700 "${GNUPGHOME}"
