#!/bin/sh
GNUPGHOME="${XDG_CONFIG_HOME}/gnupg"

if [ "$(uname -s)" = "Darwin" ]; then
  # Force use of BSD installed variant.
  /usr/bin/sed -i "" -e \
    "s#/usr/bin/pinentry-curses#${PREFIX}/bin/pinentry-mac#g" \
    "${GNUPGHOME}/gpg-agent.conf"
fi

# Import my key
MY_GPG_KEY_ID="0x06E2E2310CB5DB04"
if ! gpg  -k | grep "${MY_GPG_KEY_ID}" > /dev/null; then
    # Import Public Key
    curl -s https://keybase.io/pmonk/key.asc | gpg --import
    # Verify key as trusted.
    if gpg -k | grep "${MY_GPG_KEY_ID}" > /dev/null; then
      gpg --list-keys --fingerprint --with-colons \
        | sed -E -n -e 's/^fpr:::::::::([0-9A-F]+):$/\1:6:/p' \
          | gpg --import-ownertrust
    fi
fi
