#!/bin/sh

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

if command -v lesskey >/dev/null 2>&1 && [ ! -f "${XDG_CONFIG_HOME}/less/lesskey/output" ]; then
  lesskey -o "${XDG_CONFIG_HOME}/less/lesskey/output" "${XDG_CONFIG_HOME}/less/lesskey/input"
fi
