#!/bin/bash
# Disable Apple press-and-hold for VSCode (enables key repeat).
set -o errexit -o errtrace -o pipefail -o nounset

defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
