#!/bin/sh

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

# Remove any broken symlinks:
# non-recursively from the following directories.
find "${HOME}" -maxdepth 1 -type l ! -exec test -e {} \; -delete
find "${HOME}/.ssh" -maxdepth 1 -type l ! -exec test -e {} \; -delete

# Recursively from the following directories.
find "${XDG_CONFIG_HOME}" -type l ! -exec test -e {} \; -delete
find "${HOME}/.claude" -type l ! -exec test -e {} \; -delete
