#!/bin/sh
mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}/npm"
mkdir -p "${XDG_CONFIG_HOME:-$HOME/.config}/npm"
mkdir -p "${XDG_DATA_HOME:-$HOME/.local/share/data}/npm"
mkdir -p "${XDG_RUNTIME_DIR:-/run}/npm"
